version: '3.8'

services:
  frontend:
    build: ./
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - backend
    restart: always
    networks:
      - oht_network


  backend:
    build: ./flask_backend
    ports:
      - "127.0.0.1:5000:5000"
    expose:
      - "5000"
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@db:5432/oht_simulation
    #   - FLASK_ENV=production
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - oht_network
    volumes:
      - ./flask_backend:/app

  db:
    image: postgres:latest
    restart: always
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: password
    #   POSTGRES_DB: oht_simulation

    # ports:
    #   - "127.0.0.1:5432:5432"

    expose:
     - "5432"
    
    env_file:
      - .env
    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oht_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
        
    restart: always
    
    depends_on:
      - frontend
      - backend
    networks:
      - oht_network


networks:
  oht_network:
    driver: bridge
