version: '3.8'

services:
  frontend:
    build: ./

    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - oht_network


  backend:
    build: ./flask_backend
    ports:
      - "127.0.0.1:5000:5000"
    expose:
      - "5000"

    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - oht_network
    volumes:
      - ./flask_backend:/app

  db:
    image: postgres:latest
    restart: always


    expose:
     - "5432"
    
    env_file:
      - .env
    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oht_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
        
    restart: always
    
    depends_on:
      - frontend
      - backend
    networks:
      - oht_network


networks:
  oht_network:
    driver: bridge
