services:
  train:
    image: oht-train:latest
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: oht-train
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../datasets_pivot:/workspace/datasets_pivot:ro
      - ../datasets_dynamic:/workspace/datasets_dynamic:ro
      - ./fab_oht_layout_updated.json:/workspace/fab_oht_layout_updated.json:ro
      - ./checkpoints:/workspace/checkpoints
      - ./train.log:/workspace/train.log
    restart: "no"
